-- Definition for the full join view

config {
  type: "view",
  description: "View created from the full join of openpowerlifting and meets tables.",
  schema: "dataform",
  columns: {
    meetid: "The ID of the meet from openpowerlifting.",
    name: "The name associated with the meet.",
    sex: "The sex of the participants.",
    meetid_meets: "The ID of the meet from meets table."
  }
}

-- Select the full join results to create the view
SELECT *
FROM ${ref("full_join")}
